Repository googleapis/python-asset, pull requests merged in 2020-12, with the labels that each got.

#127 fix: remove v1beta1
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/asset_v1beta1/services.rst
  docs/asset_v1beta1/types.rst
  docs/index.rst
  google/cloud/asset_v1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1/types/__init__.py
  google/cloud/asset_v1/types/asset_service.py
  google/cloud/asset_v1beta1/__init__.py
  google/cloud/asset_v1beta1/py.typed
  google/cloud/asset_v1beta1/services/__init__.py
  google/cloud/asset_v1beta1/services/asset_service/__init__.py
  google/cloud/asset_v1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1beta1/services/asset_service/client.py
  google/cloud/asset_v1beta1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1beta1/types/__init__.py
  google/cloud/asset_v1beta1/types/asset_service.py
  google/cloud/asset_v1beta1/types/assets.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p1beta1/types/__init__.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p2beta1/types/__init__.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p4beta1/types/__init__.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/__init__.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p5beta1/types/__init__.py
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
  synth.py
  tests/unit/gapic/asset_v1/test_asset_service.py
  tests/unit/gapic/asset_v1beta1/__init__.py
  tests/unit/gapic/asset_v1beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p1beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p2beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p4beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p5beta1/test_asset_service.py
Labels: api: cloudasset, cla: yes, context: partial

#138 test: add 3.9 unit tests
  noxfile.py
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#121 chore: rename sync-repo-settings
  .github/sync-repo-settings.yaml
Labels: api: cloudasset, cla: yes

#107 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: api: cloudasset, cla: yes
