Repository googleapis/python-asset, pull requests merged in 2020-11, with the labels that each got.

#108 testing(sample): fix broken tests
  samples/snippets/quickstart_batchgetassetshistory_test.py
  samples/snippets/quickstart_searchallresources_test.py
Labels: api: cloudasset, cla: yes

#109 testing(sample): make the sample tests mandatory
  .github/sync-repo-settings.yml
Labels: api: cloudasset, automerge, cla: yes

#99 docs: remove note on editable installs
  CONTRIBUTING.rst
  google/cloud/asset_v1/services/asset_service/async_client.py
  google/cloud/asset_v1/services/asset_service/transports/base.py
  google/cloud/asset_v1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p2beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/base.py
  synth.metadata
Labels: api: cloudasset, cla: yes, context: partial

#118 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full

#119 docs(python): fix intersphinx link for google-auth
  docs/conf.py
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full

#122 chore: replace partion_key by partition_key
  google/cloud/asset_v1/types/asset_service.py
Labels: api: cloudasset, cla: yes
