Repository googleapis/python-asset, pull requests merged in 2020-09, with the labels that each got.

#81 fix(sample): mark a test with flaky
  samples/snippets/quickstart_searchallresources_test.py
  samples/snippets/requirements-test.txt
Labels: api: cloudasset, cla: yes

#86 feat: add support for per type and partition export
  .github/snippet-bot.yml
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  docs/conf.py
  google/cloud/asset/__init__.py
  google/cloud/asset_v1/__init__.py
  google/cloud/asset_v1/services/asset_service/async_client.py
  google/cloud/asset_v1/services/asset_service/client.py
  google/cloud/asset_v1/services/asset_service/transports/base.py
  google/cloud/asset_v1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1/types/__init__.py
  google/cloud/asset_v1/types/asset_service.py
  google/cloud/asset_v1/types/assets.py
  google/cloud/asset_v1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1beta1/services/asset_service/client.py
  google/cloud/asset_v1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p1beta1/services/asset_service/client.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p2beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p2beta1/services/asset_service/client.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p2beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p4beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p4beta1/services/asset_service/client.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p4beta1/services/asset_service/transports/grpc_asyncio.py
  google/cloud/asset_v1p5beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p5beta1/services/asset_service/client.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/grpc.py
  google/cloud/asset_v1p5beta1/services/asset_service/transports/grpc_asyncio.py
  noxfile.py
  samples/snippets/noxfile.py
  scripts/decrypt-secrets.sh
  synth.metadata
  tests/unit/gapic/asset_v1/test_asset_service.py
  tests/unit/gapic/asset_v1beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p1beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p2beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p4beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p5beta1/test_asset_service.py
Labels: cla: yes, context: partial

#88 chore: re-order retry
  google/cloud/asset_v1/services/asset_service/async_client.py
  google/cloud/asset_v1/services/asset_service/transports/base.py
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#95 chore: fix type annotations
  google/cloud/asset_v1/services/asset_service/async_client.py
  google/cloud/asset_v1/services/asset_service/client.py
  google/cloud/asset_v1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1beta1/services/asset_service/client.py
  google/cloud/asset_v1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p1beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p1beta1/services/asset_service/client.py
  google/cloud/asset_v1p1beta1/services/asset_service/transports/base.py
  google/cloud/asset_v1p2beta1/services/asset_service/client.py
  google/cloud/asset_v1p4beta1/services/asset_service/async_client.py
  google/cloud/asset_v1p4beta1/services/asset_service/client.py
  google/cloud/asset_v1p5beta1/services/asset_service/client.py
  synth.metadata
  tests/unit/gapic/asset_v1/test_asset_service.py
  tests/unit/gapic/asset_v1beta1/test_asset_service.py
  tests/unit/gapic/asset_v1p4beta1/test_asset_service.py
Labels: api: cloudasset, cla: yes, context: partial

#93 chore: add sphinx.ext.doctest
  docs/conf.py
  google/cloud/asset_v1/services/asset_service/async_client.py
  google/cloud/asset_v1/services/asset_service/transports/base.py
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: partial

#96 chore: add default CODEOWNERS
  .github/CODEOWNERS
Labels: api: cloudasset, automerge, cla: yes
