Repository googleapis/python-asset, pull requests merged in 2020-06, with the labels that each got.

#17 feat: release GA
  README.rst
Labels: cla: yes

#32 feat: add `search_all_resources` and `search_all_iam_policies` (via synth)
  google/cloud/asset_v1/gapic/asset_service_client.py
  google/cloud/asset_v1/gapic/asset_service_client_config.py
  google/cloud/asset_v1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1/proto/asset_service_pb2.py
  google/cloud/asset_v1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1/proto/assets_pb2.py
  google/cloud/asset_v1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p2beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p2beta1/proto/assets_pb2.py
  google/cloud/asset_v1p4beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p4beta1/proto/assets_pb2.py
  synth.metadata
  tests/unit/gapic/v1/test_asset_service_client_v1.py
Labels: cla: yes, context: partial

#44 feat(v1): add support for condition in Feed
  google/cloud/asset_v1/__init__.py
  google/cloud/asset_v1/gapic/asset_service_client.py
  google/cloud/asset_v1/gapic/enums.py
  google/cloud/asset_v1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1/proto/asset_service_pb2.py
  google/cloud/asset_v1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1/proto/assets_pb2.py
  google/cloud/asset_v1beta1/__init__.py
  google/cloud/asset_v1beta1/gapic/asset_service_client_config.py
  google/cloud/asset_v1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p1beta1/__init__.py
  google/cloud/asset_v1p1beta1/gapic/asset_service_client_config.py
  google/cloud/asset_v1p1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p2beta1/__init__.py
  google/cloud/asset_v1p2beta1/gapic/asset_service_client_config.py
  google/cloud/asset_v1p2beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p2beta1/proto/assets_pb2.py
  google/cloud/asset_v1p4beta1/__init__.py
  google/cloud/asset_v1p4beta1/gapic/asset_service_client_config.py
  google/cloud/asset_v1p4beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p4beta1/proto/assets_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#48 chore: update templates
  .flake8
  .gitignore
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  google/cloud/asset.py
  google/cloud/asset_v1/__init__.py
  google/cloud/asset_v1/gapic/asset_service_client.py
  google/cloud/asset_v1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1/proto/asset_service_pb2.py
  google/cloud/asset_v1/proto/assets_pb2.py
  google/cloud/asset_v1/types.py
  google/cloud/asset_v1beta1/__init__.py
  google/cloud/asset_v1beta1/gapic/asset_service_client.py
  google/cloud/asset_v1beta1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1beta1/types.py
  google/cloud/asset_v1p1beta1/__init__.py
  google/cloud/asset_v1p1beta1/gapic/asset_service_client.py
  google/cloud/asset_v1p1beta1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1p1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p1beta1/types.py
  google/cloud/asset_v1p2beta1/__init__.py
  google/cloud/asset_v1p2beta1/gapic/asset_service_client.py
  google/cloud/asset_v1p2beta1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1p2beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p2beta1/types.py
  google/cloud/asset_v1p4beta1/__init__.py
  google/cloud/asset_v1p4beta1/gapic/asset_service_client.py
  google/cloud/asset_v1p4beta1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1p4beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p4beta1/proto/assets_pb2.py
  google/cloud/asset_v1p4beta1/types.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
Labels: automerge, cla: yes, context: full

#51 fix: update default retry configs
  google/cloud/asset_v1/gapic/asset_service_client.py
  google/cloud/asset_v1/gapic/asset_service_client_config.py
  google/cloud/asset_v1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1/proto/asset_service_pb2.py
  google/cloud/asset_v1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1/proto/assets_pb2.py
  google/cloud/asset_v1/proto/assets_pb2_grpc.py
  google/cloud/asset_v1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1beta1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1beta1/proto/assets_pb2.py
  google/cloud/asset_v1beta1/proto/assets_pb2_grpc.py
  google/cloud/asset_v1p1beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p1beta1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1p1beta1/proto/assets_pb2.py
  google/cloud/asset_v1p1beta1/proto/assets_pb2_grpc.py
  google/cloud/asset_v1p2beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p2beta1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1p2beta1/proto/assets_pb2.py
  google/cloud/asset_v1p2beta1/proto/assets_pb2_grpc.py
  google/cloud/asset_v1p4beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p4beta1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1p4beta1/proto/assets_pb2.py
  google/cloud/asset_v1p4beta1/proto/assets_pb2_grpc.py
  synth.metadata
  synth.py
  tests/unit/gapic/v1/test_asset_service_client_v1.py
Labels: cla: yes, context: partial

#47 feat: generate v1p5beta1
  docs/gapic/v1p5beta1/api.rst
  docs/gapic/v1p5beta1/types.rst
  docs/index.rst
  google/cloud/asset_v1p5beta1/__init__.py
  google/cloud/asset_v1p5beta1/gapic/__init__.py
  google/cloud/asset_v1p5beta1/gapic/asset_service_client.py
  google/cloud/asset_v1p5beta1/gapic/asset_service_client_config.py
  google/cloud/asset_v1p5beta1/gapic/enums.py
  google/cloud/asset_v1p5beta1/gapic/transports/__init__.py
  google/cloud/asset_v1p5beta1/gapic/transports/asset_service_grpc_transport.py
  google/cloud/asset_v1p5beta1/proto/__init__.py
  google/cloud/asset_v1p5beta1/proto/asset_service_pb2.py
  google/cloud/asset_v1p5beta1/proto/asset_service_pb2_grpc.py
  google/cloud/asset_v1p5beta1/proto/assets_pb2.py
  google/cloud/asset_v1p5beta1/proto/assets_pb2_grpc.py
  google/cloud/asset_v1p5beta1/types.py
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  synth.metadata
  synth.py
  tests/unit/gapic/v1p5beta1/test_asset_service_client_v1p5beta1.py
Labels: cla: yes
