Repository googleapis/python-asset, pull requests merged in 2021-04, with the labels that each got.

#169 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full

#172 chore: add tarfile
  asset-v1-py.tar.gz
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#176 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudasset, cla: yes

#178 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudasset, automerge, cla: yes
